package com.tmaxqa.entity;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

public class CPU {
	
	private int seq;
	private String ip;
	private String info;
	
	public CPU() {
		super();
	}
	public CPU(int seq, String ip, String info) {
		super();
		this.seq = seq;
		this.ip = ip;
		this.info = info;
	}
	public int getSeq() {
		return seq;
	}
	public void setSeq(int seq) {
		this.seq = seq;
	}
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	@Override
	public String toString() {
		return "CPU [seq=" + seq + ", ip=" + ip + ", info=" + info + "]";
	}
		

}



