package com.tmaxqa.entity;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

public class Mem {
	
	private int seq;
	private String ip;
	private String info;
	private String total;
	private String used;
	private String free;
	private String shared;
	private String buffcache;
	private String avail;
	
	public Mem() {
		super();
	}
	public Mem(int seq, String ip, String info, String total, String used, String free, String shared, String buffcache,
			String avail) {
		super();
		this.seq = seq;
		this.ip = ip;
		this.info = info;
		this.total = total;
		this.used = used;
		this.free = free;
		this.shared = shared;
		this.buffcache = buffcache;
		this.avail = avail;
	}
	
	public int getSeq() {
		return seq;
	}
	public void setSeq(int seq) {
		this.seq = seq;
	}
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	public String getTotal() {
		return total;
	}
	public void setTotal(String total) {
		this.total = total;
	}
	public String getUsed() {
		return used;
	}
	public void setUsed(String used) {
		this.used = used;
	}
	public String getFree() {
		return free;
	}
	public void setFree(String free) {
		this.free = free;
	}
	public String getShared() {
		return shared;
	}
	public void setShared(String shared) {
		this.shared = shared;
	}
	public String getBuffcache() {
		return buffcache;
	}
	public void setBuffcache(String buffcache) {
		this.buffcache = buffcache;
	}
	public String getAvail() {
		return avail;
	}
	public void setAvail(String avail) {
		this.avail = avail;
	}
	@Override
	public String toString() {
		return "Mem [seq=" + seq + ", ip=" + ip + ", info=" + info + ", total=" + total + ", used=" + used + ", free="
				+ free + ", shared=" + shared + ", buffcache=" + buffcache + ", avail=" + avail + "]";
	}

}



