package com.tmaxqa.entity;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

public class Users {
	

	private String id;
	private String pw;
	private String dept;
	private String name;

	public Users() {
		super();
	}

	public Users(String id, String pw, String dept, String name) {
		super();
		this.id = id;
		this.pw = pw;
		this.dept = dept;
		this.name = name;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPw() {
		return pw;
	}

	public void setPw(String pw) {
		this.pw = pw;
	}

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Users [id=" + id + ", pw=" + pw + ", dept=" + dept + ", name=" + name + "]";
	}

	

}



